### ISSUE TITLE
Race condition found when changing a global role/local role

### ISSUE THREAD

**Issue by desdic** [One-com/chef_delivery#2]
1) If you have a global role and a local role with the same name the local role gets uploadet
2) If you change the global role the global role gets uploading overwriting the local role

**Comment by storpipfugl** [comment]
The best way to solve this is to not have name collisions between local and global roles. Suggest to update docs with description of this and leave any enforcement of this to users (e.g. using git hooks)

**Comment by desdic** [comment]
Added a patch for handling atomic changes when dealing with deleting roles

**Comment by sa7dse** [comment]
Not pushed yet i assume?

**Comment by desdic** [comment]
Its pushed in the same branch (race) 5f2fe4f

**Comment by storpipfugl** [comment]
Fixed by v0.4.0
