### ISSUE TITLE
Question: Does chef_delivery upload berkshelf managed cookbooks?

### ISSUE THREAD

**Issue by brianwallace** [One-com/chef_delivery#4]
I found this project after unsuccessfully attempting to get Facebooks Grocery Delivery up and running.  I like `chef_delivery` as it also manages clients, environments, nodes and users.

Question: Does `chef_delivery` upload berkshelf managed cookbooks?  If one uses berkshelf for managing dependent cookbooks, can chef_delivery upload those?

**Comment by desdic** [comment]
All it does is the same as 'knife cookbook upload ...'  so it does not look at if a cookbook is handled by kitchen or berkshelf. It just pulls it from the repository and upload it

**Comment by brianwallace** [comment]
@desdic, thanks for the quick response!

Since I depend on berkshelf for managing cookbook dependencies, I don't think `one-com/chef_delivery` will fit our needs.  (But it looks like a great product!).  Let me know if I am missing something or if others who also use berkshelf have been successful with `one-com/chef_delivery`.

**Comment by storpipfugl** [comment]
Updated README.md with section on cookbook dependencies
